name: publish
on: 
  push:
    branches:
      - deploy

jobs:
  publish:
    name: Build and Publish RedditMap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npx gulp build
      - name: Publish Site
        run: npx gulp publish --environment=production-www
        env:
          AWS_ACCESS_KEY_ID: AKIAVLPQTNXLIINXCGOO
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: us-east-1
